services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
      - "node_modules:/app/node_modules"
    environment:
      - NEXT_PUBLIC_API_URL=https://whatbackend.onrender.com/api/v1
    command: npm run dev -- -p 80

volumes:
  node_modules:
